---
- name: yum install with_items
  hosts: patti_smith
  tasks:
    - name: yum install packages 
      yum:
        name: "{{ item }}"
        state: latest
      loop:
        - dstat
        - lsof
        - mailx
        - rsync
        - tree
        - vim-enhanced
        - git
        - whois
        - iptables-services
