---

- hosts: localhost
  vars_files:
    - mysecrets.yml
  tasks:
    - debug:
        msg: "The username is {{ username }} and password is {{ password }}"
    - debug:
        msg: "I am going to install {{ packages }}"
    - debug:
        msg: "{{ apikey }}"
