---
- hosts: all
  remote_user: vagrant
  become: true
  tasks:
    - group:
        name: devops
        state: present
    - name: create devops user with admin privileges
      user:
        name: devops
        comment: "Devops User"
        uid: 2001
        group: devops
    - name: install htop package
      action: apt name=htop state=present update_cache=yes
- hosts: www
  user: vagrant
  become: true
  tasks:
#    - name: Add an Apt signing key, uses whichever key is at the URL
#      ansible.builtin.apt_key:
#        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
#        state: present
#    - name: add official nginx repository
#      apt_repository:
#        repo: 'deb http://nginx.org/packages/ubuntu/ lucid nginx'
    - name: install nginx web server and ensure its at the latest version
      apt:
        name: nginx
        state: latest
    - name: start nginx service
      service:
        name: nginx
        state: started
