# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  if Vagrant.has_plugin?("vagrant-vbguest") then
     config.vbguest.auto_update = false
  end
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.define "control" do |control|
    control.vm.network :private_network, ip: "192.168.61.10"
  end

  config.vm.define "db" do |db|
    db.vm.network :private_network, ip: "192.168.61.11"
  end

  config.vm.define "dbel" do |db|
    db.vm.network :private_network, ip: "192.168.61.14"
    db.vm.box = "opscode_centos-6.5-i386"
  end

  config.vm.define "www" do |www|
    www.vm.network :private_network, ip: "192.168.61.12"
  end

  config.vm.define "lb" do |lb|
    lb.vm.network :private_network, ip: "192.168.61.13"
  end
end
