---
- hosts: www
  remote_user: vagrant
  become: true
  pre_tasks:
    - shell: echo 'I":" Beginning to configure web server...'
      register: foo
    - debug: msg="{{ foo.stdout }}"
  roles:
  - nginx
  post_tasks:
    - shell: echo 'I":" Done conifiguring nginx web server...'
      register: bar
    - debug: msg="{{ bar.stdout }}"
