---
# defaults file for bind
needed_packages:
  - bind
  - bind-utils
acl_trusted:
  - 192.168.50.8
  - 192.168.50.9
  - 192.168.50.10
type:
   master
zones: 
  - mymac.crupi.net
A_rec:
  - arec: ns1
    dom:  mymac.crupi.net
    ip:   192.168.50.8
  - arec: ns2
    dom:  mymac.crupi.net
    ip:   192.168.50.9
  - arec: host1
    dom:  mymac.crupi.net
    ip:   192.168.50.10
db_ips:
   - 192.168.50
primary: 
    dom : mymac.crupi.net
    ip:   192.168.50.8
secondary: 
    dom : mymac.crupi.net
    ip:   192.168.50.9
ptr_records:
   - ptr: 8
     host: ns1
     domain: mymac.crupi.net
   - ptr: 9
     host : ns2
     domain: mymac.crupi.net
   - ptr: 10
     host : host1
     domain: mymac.crupi.net
