---
# defaults file for bind
needed_packages:
  - bind
  - bind-utils
acl_trusted:
  - 192.168.50.8
  - 192.168.50.9
  - 192.168.50.10
  - 192.168.55.8
  - 192.168.55.9
  - 192.168.55.10
zones: 
  - zone1: primary
    dom: mymac.crupi.net
    subnet:  192.168.50
    type: master
  - zone2: primary
    dom: mymac.beatles.net
    subnet:  192.168.55
    type: master
primary: 
    dom : mymac.crupi.net
    ip:   192.168.50.8
secondary: 
    dom : mymac.crupi.net
    ip:   192.168.50.9
A_rec:
  - arec: ns1
    dom:  mymac.crupi.net
    ip:   192.168.50.8
  - arec: ns2
    dom:  mymac.crupi.net
    ip:   192.168.50.9
  - arec: host1
    dom:  mymac.crupi.net
    ip:   192.168.50.10
  - arec: host2
    dom:  mymac.beatles.net
    ip:   192.168.55.8
  - arec: host2
    dom:  mymac.beatles.net
    ip:   192.168.55.9
  - arec: host3
    dom:  mymac.beatles.net
    ip:   192.168.55.10
ptr_records:
   - ptr: 8
     host: ns1
     domain: mymac.crupi.net
   - ptr: 9
     host : ns2
     domain: mymac.crupi.net
   - ptr: 10
     host : host1
     domain: mymac.crupi.net
   - ptr: 9
     host : host2
     domain: mymac.beatles.net
   - ptr: 10
     host : host3
     domain: mymac.beatles.net
