---

# Enabled the repos needed to install our software stack
##################################################################################################
- debug:
    msg: "**** In install-ubuntu.yml  6969 *****"

- name: update cache and install the system packages
  apt:
    name: "{{ item }}"
    update_cache: "yes"
  loop: "{{ system_packages }}"

- name: add the apt keys from a key server
  apt_key:
    keyserver: "{{ item.key_server }}"
    id: "{{ item.key }}"
  loop: "{{ repo_keys }}"

- name: add the apt keys from a URL
  apt_key:
    url: "{{ item }}"
    state: present
  loop: "{{ repo_keys_url }}"

- name: install the repo packages
  apt_repository:
    repo: "{{ item }}"
    state: "present"
  loop: "{{ repo_packages }}"

# Install the packages we require for our stack
##################################################################################################

- name: install the stack packages
  apt:
    name: "{{ item }}"
    state: "latest"
  loop: "{{ stack_packages + extra_packages }}"
