---
- name: create nginx docroot
  file:
     path: "{{ wp_docroot }}"
     state: directory
     owner: "{{ wp_user }}"
     group: "{{ wp_group }}"
- name: download wordpress
  command: /usr/bin/wget -c https://wordpress.org/latest.tar.gz
  args:
     chdir: "{{ wp_srcdir }}"
     creates: "{{ wp_srcdir }}/latest.tar.gz"
  register: wp_download
- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: "{{ wp_srcdir }}"
    owner: nginx
    group: nginx
    mode: '0777'
- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: "{{ wp_srcdir }}/latest.tar.gz"
    owner: nginx
    group: nginx
    mode: '0644'
- name: Delete existing wordpress folder
  file:
    path: "{{ wp_docroot }}/{{ wp_sitedir }}/wordpress"
    state: absent
- name: extract wordpress
  shell: "tar xzf latest.tar.gz && mv wordpress \
  {{ wp_docroot }}/{{ wp_sitedir }}"
  args:
     chdir: "{{ wp_srcdir }}"
  register: extract_wordpress
  when: wp_download.rc == 0
