# -*- mode: ruby -*-
# vi: set ft=ruby :

API_VERSION  = "2"
DOMAIN       = "nip.io"
PRIVATE_KEY  = "~/.ssh/id_rsa"
PUBLIC_KEY   = '~/.ssh/id_rsa.pub'
CENTOS_IP    = '192.168.50.8'
CENTOS_BOX   = 'centos/7'
CENTOS_IP2   = '192.168.50.9'
CENTOS_BOX2  = 'centos/7'
CENTOS_IP3   = '192.168.50.10'
CENTOS_BOX3  = 'centos/7'

Vagrant.configure(API_VERSION) do |config|

  config.vm.define "centos" do |centos|
      centos.vm.boot_timeout = 2400
      centos.vm.box = CENTOS_BOX
      centos.vm.network "private_network", ip: CENTOS_IP
      centos.vm.host_name = CENTOS_IP + '.' + DOMAIN
      centos.ssh.insert_key = false
      centos.ssh.private_key_path = [PRIVATE_KEY, "~/.vagrant.d/insecure_private_key"]
      centos.vm.provision "file", source: PUBLIC_KEY, destination: "~/.ssh/authorized_keys"

      if Vagrant.has_plugin?("vagrant-vbguest")
        centos.vbguest.auto_update = true
      end

      centos.vm.provider "virtualbox" do |v|
        v.memory = "2024"
        v.cpus = "2"
      end

      centos.vm.provider "vmware_fusion" do |v|
        v.vmx["memsize"] = "2024"
        v.vmx["numvcpus"] = "2"
      end
  end
  config.vm.define "centos2" do |centos2|
      centos2.vm.boot_timeout = 2400
      centos2.vm.box = CENTOS_BOX2
      centos2.vm.network "private_network", ip: CENTOS_IP2
      centos2.vm.host_name = CENTOS_IP2 + '.' + DOMAIN
      centos2.ssh.insert_key = false
      centos2.ssh.private_key_path = [PRIVATE_KEY, "~/.vagrant.d/insecure_private_key"]
      centos2.vm.provision "file", source: PUBLIC_KEY, destination: "~/.ssh/authorized_keys"

      if Vagrant.has_plugin?("vagrant-vbguest")
        centos2.vbguest.auto_update = true
      end

      centos2.vm.provider "virtualbox" do |v|
        v.memory = "2024"
        v.cpus = "2"
      end

      centos2.vm.provider "vmware_fusion" do |v|
        v.vmx["memsize"] = "2024"
        v.vmx["numvcpus"] = "2"
      end
  end
config.vm.define "centos3" do |centos3|
      centos3.vm.boot_timeout = 2400
      centos3.vm.box = CENTOS_BOX3
      centos3.vm.network "private_network", ip: CENTOS_IP3
      centos3.vm.host_name = CENTOS_IP3 + '.' + DOMAIN
      centos3.ssh.insert_key = false
      centos3.ssh.private_key_path = [PRIVATE_KEY, "~/.vagrant.d/insecure_private_key"]
      centos3.vm.provision "file", source: PUBLIC_KEY, destination: "~/.ssh/authorized_keys"

      if Vagrant.has_plugin?("vagrant-vbguest")
        centos3.vbguest.auto_update = true
      end

      centos3.vm.provider "virtualbox" do |v|
        v.memory = "2024"
        v.cpus = "2"
      end

      centos3.vm.provider "vmware_fusion" do |v|
        v.vmx["memsize"] = "2024"
        v.vmx["numvcpus"] = "2"
      end
  end
end
