---
# defaults file for roles/stack-install

# Define the default repos
##################################################################################################

repo_packages:
  - "epel-release"
  - "https://repo.ius.io/ius-release-el7.rpm"
  - "http://rpms.remirepo.net/enterprise/remi-release-7.rpm"
nginx_repo:
  name: "nginx"
  description: "The mainline NGINX repo"
  baseurl: "http://nginx.org/packages/mainline/centos/7/$basearch/"
  gpgcheck: "no"
  enabled: "yes"

# Define the default packages
##################################################################################################

packages_remove:
  - "mariadb-libs.x86_64"

system_packages:
  - "mariadb101u"
  - "mariadb101u-server"
  - "mariadb101u-config"
  - "mariadb101u-common"
  - "mariadb101u-libs"
  - "MySQL-python"
  - "postfix"
  - "policycoreutils-python"

stack_packages:
  - "nginx"
  - "php74"
  - "php74-bcmath"
  - "php74-cli"
  - "php74-common"
  - "php74-dba"
  - "php74-fpm"
  - "php74-fpm-nginx"
  - "php74-gd"
  - "php74-intl"
  - "php74-json"
  - "php74-mbstring"
  - "php74-mysqlnd"
  - "php74-process"
  - "php74-snmp"
  - "php74-soap"
  - "php74-xml"
  - "php74-xmlrpc"

extra_packages:
  - "vim-enhanced"
  - "git"
  - "unzip"
