---
# tasks file for resolv
- name: Distribution
  debug: msg="{{ ansible_distribution }}"
- name: Distribution version
  debug: msg="{{ ansible_distribution_version}}"
- name: Distribution major version
  debug: msg="{{ ansible_distribution_major_version }}"
- name: install the needed packages for bind.
  yum:
    name: "{{ item }}"
    state: "installed"
  loop: "{{ needed_packages }}"
- name: update /etc/resolv.conf
  template:
    src: resolv.j2
    dest: /etc/resolv.conf
    owner: root
    mode: 0644
- name: add dns=none after NetworkManager.conf
  lineinfile:
    path: /etc/NetworkManager/NetworkManager.conf
    insertafter: '^\[main\]'
    line: "dns=none"
- name: Start and enable NetworkManager
  systemd:
    name: NetworkManager.service
    state: restarted
    daemon_reload: true
    enabled: true
