---

# Define the default repos
##################################################################################################

repo_packages:
#  - "deb [arch=amd64,i386] http://mirror.sax.uk.as61049.net/mariadb/repo/10.1/ubuntu {{ ansible_distribution_release }} main"
  - "deb [arch=amd64,i386] http://nyc2.mirrors.digitalocean.com/mariadb/repo/10.1/ubuntu  {{ ansible_distribution_release }} main"
  - "deb http://nginx.org/packages/mainline/ubuntu/ {{ ansible_distribution_release }} nginx"
  - "deb-src http://nginx.org/packages/mainline/ubuntu/ {{ ansible_distribution_release }} nginx"

repo_keys:
  - { key_server: "keyserver.ubuntu.com", key: "0xF1656F24C74CD1D8" }

repo_keys_url:
  - "http://nginx.org/keys/nginx_signing.key"

# Define the default packages
##################################################################################################

system_packages:
  - "software-properties-common"
  - "acl"
  - "python-mysqldb"

stack_packages:
  - "nginx"
  - "mariadb-server"
  - "php"
  - "php-cli"
  - "php-fpm"
  - "php-gd"
  - "php-json"
  - "php-mbstring"
  - "php-mysqlnd"
  - "php-soap"
  - "php-xml"
  - "php-xmlrpc"

extra_packages:
  - "vim"
  - "git"
  - "unzip"
